### ISSUE TITLE
After Upgrade Baileys

### ISSUE THREAD

**Issue by mdestafadilah** [andresayac/baileys-api#4]
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.readFromFile (/www/wwwroot/SERVER_URL/node_modules/@whiskeysockets/baileys/lib/Store/make-in-memory-store.js:413:35)
    at createSession (file:///www/wwwroot/SERVER_URL/whatsapp.js:97:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by mdestafadilah** [comment]
after clone again. it's gone. running as well.
